#!/bin/sh

echo "\n===> Netoyage\n"
find . -iname "*Icon*" -o -iname "*DS*" -exec rm {} \;

echo "\n===> Make clean\n"
make clean

echo "\n===> Pull\n"
hg pull

echo "\n===> Update\n"
hg update

while true; do
    read -p "Est ce que tu as compilé ? (yes/no): " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "yes or no ?";;
    esac
done

while true; do
    read -p "Tu veux merger ? (yes/no): " yn
    case $yn in
        [Yy]* ) echo "\n===> Merge\n"; hg merge; break;;
        [Nn]* ) break;;
        * ) echo "yes or no ?";;
    esac
done

while true; do
    read -p "Tu veux faire la doc ? (yes/no) (eviter de la faire trop souvent): " yn
    case $yn in
        [Yy]* ) echo "\n===> Doxygen\n"; doxygen doc/Doxyfile; break;;
        [Nn]* ) break;;
        * ) echo "yes or no ?";;
    esac
done

echo "\n===> Commit\n"
while true; do
    read -p "Commentaire: " com
    case $com in
        * ) echo "\nTon commentaire: \"$com\""; hg commit -m "$com"; break;;
    esac
done

echo "\n===> Push\n"
hg push

echo "\n===> Fin\n"
